"""Add prep_style column to RecipeIngredient

Revision ID: 06e3429adcbd
Revises: f71152956760
Create Date: 2026-03-11 09:12:59.005639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e3429adcbd'
down_revision = 'f71152956760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_style', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_column('prep_style')

    # ### end Alembic commands ###
