"""add recipe source tracking

Revision ID: 1776963fad5b
Revises: 4d006fb77b37
Create Date: 2026-02-27 09:23:26.587299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1776963fad5b'
down_revision = '4d006fb77b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_input', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), server_default='manual', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('source_type')
        batch_op.drop_column('source_input')

    # ### end Alembic commands ###
