"""add_status_to_ingredient

Revision ID: 17ea4babf013
Revises: 1bd49ea45b5a
Create Date: 2026-02-22 07:05:26.529109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ea4babf013'
down_revision = '1bd49ea45b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.create_index(batch_op.f('ix_ingredient_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
