"""Rename is_basic_ingredient to is_staple and drop is_original

Revision ID: 3568e8d06b37
Revises: bd1bac9cdda4
Create Date: 2026-02-24 07:54:58.549186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3568e8d06b37'
down_revision = 'bd1bac9cdda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('is_basic_ingredient', new_column_name='is_staple')
        batch_op.drop_column('is_original')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_original', sa.BOOLEAN(), server_default='0', nullable=False))
        batch_op.alter_column('is_staple', new_column_name='is_basic_ingredient')

    # ### end Alembic commands ###
