"""link ingredients to sub-recipes

Revision ID: 37c4283fbd16
Revises: 6875ae0d4c45
Create Date: 2026-03-01 06:45:42.160911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c4283fbd16'
down_revision = '6875ae0d4c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'recipe', ['sub_recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sub_recipe_id')

    # ### end Alembic commands ###
