"""add data_source to ingredients

Revision ID: 4d006fb77b37
Revises: 5aa70121f4db
Create Date: 2026-02-27 06:50:56.728071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d006fb77b37'
down_revision = '5aa70121f4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source', sa.String(length=50), server_default='placeholder', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('data_source')

    # ### end Alembic commands ###
