"""Add primary_resource_id to Recipe and Ingredient

Revision ID: 51ce132a8f71
Revises: 37c4283fbd16
Create Date: 2026-03-04 07:57:03.230286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ce132a8f71'
down_revision = '37c4283fbd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_resource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resource', ['primary_resource_id'], ['id'])

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_resource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resource', ['primary_resource_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('primary_resource_id')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('primary_resource_id')

    # ### end Alembic commands ###
