"""Add sodium tracking

Revision ID: 5aa70121f4db
Revises: b0cd3a802f36
Create Date: 2026-02-26 10:43:10.913087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa70121f4db'
down_revision = 'b0cd3a802f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sodium_mg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('total_sodium_mg')

    # ### end Alembic commands ###
