"""Add status content management to resources

Revision ID: 619bcdf7c164
Revises: b52f5d3b67cc
Create Date: 2026-02-16 10:28:30.695839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619bcdf7c164'
down_revision = 'b52f5d3b67cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_resource_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
