"""expand user interactions

Revision ID: 6875ae0d4c45
Revises: 1776963fad5b
Create Date: 2026-02-28 07:17:01.484742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6875ae0d4c45'
down_revision = '1776963fad5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipe_interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_made', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_photos', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipe_interaction', schema=None) as batch_op:
        batch_op.drop_column('user_photos')
        batch_op.drop_column('comment')
        batch_op.drop_column('rating')
        batch_op.drop_column('is_made')

    # ### end Alembic commands ###
