"""Added order_index

Revision ID: 698f1c8b3e3d
Revises: b1fc8035f9ed
Create Date: 2026-03-13 08:01:29.006782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698f1c8b3e3d'
down_revision = 'b1fc8035f9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_sandbox_preset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_sandbox_preset', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
