"""Add base_servings to Recipe

Revision ID: 85ecc0204805
Revises: f8fa337bf32a
Create Date: 2026-02-26 06:22:19.383281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ecc0204805'
down_revision = 'f8fa337bf32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_servings', sa.Integer(), server_default='4', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('base_servings')

    # ### end Alembic commands ###
