"""add estimated_minutes and global_order_index to instruction table

Revision ID: a5fa166dfd1f
Revises: 3568e8d06b37
Create Date: 2026-02-24 12:18:03.295767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fa166dfd1f'
down_revision = '3568e8d06b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('global_order_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_column('global_order_index')
        batch_op.drop_column('estimated_minutes')

    # ### end Alembic commands ###
