"""Added social_hooks to Recipe

Revision ID: a6150b714186
Revises: f5921c1e290c
Create Date: 2026-03-09 07:12:31.435286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6150b714186'
down_revision = 'f5921c1e290c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_hooks', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('social_hooks')

    # ### end Alembic commands ###
