"""Add StyleSandboxRun

Revision ID: a89796615dbb
Revises: 06e3429adcbd
Create Date: 2026-03-13 06:14:55.001089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89796615dbb'
down_revision = '06e3429adcbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_sandbox_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('preset_name', sa.String(length=100), nullable=False),
    sa.Column('test_item', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_sandbox_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_sandbox_run_preset_name'), ['preset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_sandbox_run_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_sandbox_run_test_item'), ['test_item'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_sandbox_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_sandbox_run_test_item'))
        batch_op.drop_index(batch_op.f('ix_style_sandbox_run_scope'))
        batch_op.drop_index(batch_op.f('ix_style_sandbox_run_preset_name'))

    op.drop_table('style_sandbox_run')
    # ### end Alembic commands ###
