"""Add score_image to RecipeEvaluation

Revision ID: aa7d615321fd
Revises: 553554e09254
Create Date: 2026-02-21 07:54:06.382882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7d615321fd'
down_revision = '553554e09254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_image', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_evaluation', schema=None) as batch_op:
        batch_op.drop_column('score_image')

    # ### end Alembic commands ###
