"""Add full nutrition tracking constraints to recipe model

Revision ID: b0cd3a802f36
Revises: b9a60338dc8e
Create Date: 2026-02-26 10:04:14.360848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cd3a802f36'
down_revision = 'b9a60338dc8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_saturated_fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cholesterol_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_calcium_mg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_potassium_mg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('total_potassium_mg')
        batch_op.drop_column('total_calcium_mg')
        batch_op.drop_column('total_cholesterol_mg')
        batch_op.drop_column('total_saturated_fat')

    # ### end Alembic commands ###
