"""Update StyleSandboxPreset scope

Revision ID: b1fc8035f9ed
Revises: a89796615dbb
Create Date: 2026-03-13 07:29:52.851634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fc8035f9ed'
down_revision = 'a89796615dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_sandbox_preset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=100), server_default='ingredient', nullable=False))
        batch_op.drop_index(batch_op.f('ix_style_sandbox_preset_name'))
        batch_op.create_index(batch_op.f('ix_style_sandbox_preset_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_sandbox_preset_scope'), ['scope'], unique=False)
        batch_op.create_unique_constraint('uq_style_sandbox_preset_scope_name', ['scope', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_sandbox_preset', schema=None) as batch_op:
        batch_op.drop_constraint('uq_style_sandbox_preset_scope_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_style_sandbox_preset_scope'))
        batch_op.drop_index(batch_op.f('ix_style_sandbox_preset_name'))
        batch_op.create_index(batch_op.f('ix_style_sandbox_preset_name'), ['name'], unique=True)
        batch_op.drop_column('scope')

    # ### end Alembic commands ###
