"""add_resource_table

Revision ID: b52f5d3b67cc
Revises: cb1d61e3de76
Create Date: 2026-02-12 09:03:12.940301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52f5d3b67cc'
down_revision = 'cb1d61e3de76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_slug'), ['slug'], unique=True)

    op.create_table('resource_relations',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'related_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_relations')
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_slug'))

    op.drop_table('resource')
    # ### end Alembic commands ###
