"""Add full spectrum nutrition columns

Revision ID: b9a60338dc8e
Revises: 85ecc0204805
Create Date: 2026-02-26 09:51:36.812419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a60338dc8e'
down_revision = '85ecc0204805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cholesterol_mg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcium_mg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('potassium_mg_per_100g', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('potassium_mg_per_100g')
        batch_op.drop_column('calcium_mg_per_100g')
        batch_op.drop_column('cholesterol_mg_per_100g')

    # ### end Alembic commands ###
