"""refactor tiktok source for two stage pipeline

Revision ID: bb735c1445c7
Revises: 51ce132a8f71
Create Date: 2026-03-08 09:49:01.416342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb735c1445c7'
down_revision = '51ce132a8f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_type', sa.String(length=50), server_default='UNKNOWN', nullable=False))
        batch_op.add_column(sa.Column('raw_caption', sa.Text(), nullable=True))
        batch_op.drop_column('extracted_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_json', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False))
        batch_op.drop_column('raw_caption')
        batch_op.drop_column('format_type')

    # ### end Alembic commands ###
