"""Added has_transparent_image column to Ingredient

Revision ID: c1325fa5237c
Revises: a6150b714186
Create Date: 2026-03-10 09:37:00.704453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1325fa5237c'
down_revision = 'a6150b714186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_transparent_image', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('has_transparent_image')

    # ### end Alembic commands ###
