"""add recipe status state machine

Revision ID: cdb09877fc20
Revises: aa7d615321fd
Create Date: 2026-02-21 08:50:12.428339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb09877fc20'
down_revision = 'aa7d615321fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
        batch_op.create_index(batch_op.f('ix_recipe_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
