"""Added source_image_filename to Recipe

Revision ID: f5921c1e290c
Revises: bb735c1445c7
Create Date: 2026-03-08 10:16:34.154045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5921c1e290c'
down_revision = 'bb735c1445c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_image_filename', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('source_image_filename')

    # ### end Alembic commands ###
