"""Add gram_weight to RecipeIngredient

Revision ID: f8fa337bf32a
Revises: ff1dc45cc87e
Create Date: 2026-02-25 12:04:27.582279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8fa337bf32a'
down_revision = 'ff1dc45cc87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gram_weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_column('gram_weight')

    # ### end Alembic commands ###
