"""add component_images to recipe table

Revision ID: ff1dc45cc87e
Revises: a5fa166dfd1f
Create Date: 2026-02-25 07:11:08.241685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1dc45cc87e'
down_revision = 'a5fa166dfd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_images', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('component_images')

    # ### end Alembic commands ###
